### ISSUE TITLE
TransformBlock

### ISSUE THREAD

**Issue by alisterburt** [gutsche-lab/peepingtom#14]
TransformBlock should be a block containing points and orientations (much like a ParticleBlock). 

These points and orientations are relative to a point at the origin and should describe the relative positions and orientations of subparticles compared to oriented particles in a ParticleBlock

This will eventually be used to mirror the functionality of dpktbl.subbox.tableOnTable from dynamo for applying - equvalent to the table which is applied on an existing table in that implementation

**Comment by brisvag** [comment]
closed by #34 .
