### ISSUE TITLE
Rescaling data

### ISSUE THREAD

**Issue by alisterburt** [gutsche-lab/peepingtom#19]
So far, we haven't paid any attention to the need to rescale data

A world coordinates system has been implemented in napari/napari#1539 which we can definitely take advantage of but we also need to check about rescaling etc

A safe bet is to use angstroms as our physical units everywhere and, if possible, pixel sizes should be inferred from the data or optionally provided by the user

**Comment by brisvag** [comment]
This is relevant especially for handling template matching results, since they come out rescaled from 0 to 1. We need to figure out:
1) when we can retrieve the scale (is it present in the starfile, or can we only retrieve it from the images?)
2) where we want to store this information (probably some attribute in the particle block)
3) how to cleanly deal with this at napari level

**Comment by alisterburt** [comment]
Definitely, a combination of this and #50 all existing under the same '.star' file are why I thought having one all encompassing peeper was maybe a lofty goal.

Currently we can retrieve scale from RELION 3.1 star files, user input and the image files themselves, none of which are guaranteed to be correct
- dynamo doesn't write pixel sizes into the headers of volumes as standard
- RELION <3.1 STAR files don't contain pixel size info, some (but not all) of them contain magnification and detector pixel size info
- Warp STAR files from template matching have no info about the volume they come from (to infer position) or the pixel size of that volume

Hard problem, definitely needs to be handled with care.

One solution is just to always ask for a pixel size, although that's quickly annoying if you know that the information is available in the files you provided

We could also explicitly handle each case and provide warnings when we know things are likely wrong?

**Comment by brisvag** [comment]
I'm gonna think about it a bit. I think it should be possible to guess some things, fetch others from files, and as last resort ask for what's missing.

**Comment by brisvag** [comment]
Closed by #69 .
