### ISSUE TITLE
Layer management for DataCrates

### ISSUE THREAD

**Issue by alisterburt** [gutsche-lab/peepingtom#29]
Currently, we have basic systems in place for generating multiple `DataCrate` objects from metadata files which act as containers for multiple objects which exist within the same 3d reference frame across a dataset e.g. tomogram, cc-volume, template matched positions, refinements

We need a system for easily switching between `DataCrate`s from within the napari viewer

@brisvag you mentioned that this is currently made more difficult by a problem on the napari side, I couldn't find the issue, would you mind linking it when you get a sec?

**Comment by brisvag** [comment]
There are issues with qt objects complaining when layers are removed and added. In general, the layer list in napari is a bit finnicky at the moment. Maybe 0.4.1 fixes some of thes issues though. The relevant issues I can think of are: https://github.com/napari/napari/issues/1846, https://github.com/napari/napari/issues/1850 and https://github.com/napari/napari/pull/1504.

**Comment by brisvag** [comment]
Somewhat obsolete with #68, but still relevant for how DataSet should handle this. Probably will use napari's layer groups once thay're rolled out!

**Comment by alisterburt** [comment]
Update from discussion, current idea is to implement our own volume switcher (probably based on napari-imc) and have the data within each volume be handled by layer groups in napari where appropriate

**Comment by brisvag** [comment]
Very much closed :)
