### ISSUE TITLE
Eulerangles helper fails if only one matrix is passed

### ISSUE THREAD

**Issue by brisvag** [gutsche-lab/peepingtom#36]
I fixed the current `_io` tests by creating a dataframe with 2 lines. If instead it gets passed just one line, and only one matrix is generated, `EulerAngleHelper.invert_rotation_matrices()` fails.

**Comment by alisterburt** [comment]
this is because the call to `np.transpose` assumes 3 axes - fixed by changing to `np.swapaxes` - dealing with euler angles still appears to be being refactored, will add this fix to my new version for relion in #60

**Comment by brisvag** [comment]
Cool!

**Comment by alisterburt** [comment]
closed by #61
