### ISSUE TITLE
Base Classes

### ISSUE THREAD

**Issue by brisvag** [gutsche-lab/peepingtom#49]
So far we've been calling eveything a `DataBlock`, despite the name change. I feel like it's better to just go back to `DataBlock` being the base classe, and calling the current `DataBlock` something like `Uni/Single/Simple/MonoBlock`.

**Comment by alisterburt** [comment]
I like `SimpleBlock` the most, with the definition being that it's a data
structure which can be visualised and cannot be expressed as a combination
of existing `SimpleBlock`s?

**Comment by brisvag** [comment]
That sounds good to me!

**Comment by brisvag** [comment]
closed by #48.
