### ISSUE TITLE
Relion format update

### ISSUE THREAD

**Issue by brisvag** [gutsche-lab/peepingtom#50]
How do we deal with this? What additional info does it bring to us, if any?

**Comment by alisterburt** [comment]
not sure what you're referring to with this, do you mean the update of the convention in alisterburt/eulerangles?

**Comment by brisvag** [comment]
No, I'm referring to the fact that the new `starfile` format spits out multple dataframe. Or have I misunderstood?

**Comment by alisterburt** [comment]
ahhh gotcha!

Yes these are RELION 3.1+ STAR files with optics group information at the beginning.

We definitely need to be able to gracefully handle both cases, ideally without a user having to know about the existence of an alternative format from the one they have (i.e. let's try not to require a flag)

One additional piece of useful info is the pixel size is in the optics group information!! as well as the number of pixels in the box for each particle. We could use the pixel size info to move towards some rescaling functionality (#19)

**Comment by brisvag** [comment]
closed by #48 .
