### ISSUE TITLE
Read dynamo `em` files

### ISSUE THREAD

**Issue by brisvag** [gutsche-lab/peepingtom#51]
It would be nice to quickly look at these files in napari. I couldn't find the format specification anywhere, so we should probably ask Daniel.

**Comment by alisterburt** [comment]
Yep agreed! From memory I think his implementation is a C++ implementation, I doubt he has a ‘spec’ somewhere knowing him but I could be wrong

**Comment by brisvag** [comment]
closed by #48 .
