### ISSUE TITLE
read starfile puts everything in properties

### ISSUE THREAD

**Issue by brisvag** [gutsche-lab/peepingtom#66]
I don't think we should dump all the columns of a starfile into the properties of a particleblock.
At the very least, we should remove positions, euler angles and other already used columns!

**Comment by alisterburt** [comment]
I thought about this when doing it and actually disagree. I initially thought the same, but then I thought about the possibility of a GUI which lets you explore the relationships between properties of a set of particle blocks (does CC correlate with defocus, does class assignment correlate to tilt angle) so thought these things could be useful

**Comment by brisvag** [comment]
Ok, that's fine, but we should defnitely get rid of duplicate data, no? Is there any reason to keep shifts?

**Comment by alisterburt** [comment]
yeah definitely, seeing which particles shifted most during a refinement,
seeing if that correlates to defocus, that kinda thing :)

**Comment by brisvag** [comment]
Ok, then we can keep it all! We should probably add some level of protection, to make sure none of these preexisting columns in the dataframe are overwritten by some arbitrary property by mistake

**Comment by alisterburt** [comment]
Yeah that sounds like a good idea, not sure if this is possible as a dataframe/how to go about it though - do you have any ideas?

**Comment by brisvag** [comment]
I think we can simply add a check on `__setitem__` of the propertyblock that raises an error if you try to set those properties again? And we could hold a list of the properties created at instantiation, so only those ones are protected.
