### ISSUE TITLE
Empty particleblocks (and probably other blocks) break things

### ISSUE THREAD

**Issue by brisvag** [gutsche-lab/peepingtom#67]
We should handle gracefully empty blocks. Currently, particle depictors crash with an empty dataset, which can happen if you use `ParticleBlock.if_properties()`.

It's probably a problem elsewhere.

**Comment by alisterburt** [comment]
okay cool, good to know!

**Comment by brisvag** [comment]
This was addressed (hopefully) in #69. If anything comes up, we can reopen.
