### ISSUE TITLE
The circle of life of a DataSet

### ISSUE THREAD

**Issue by brisvag** [gutsche-lab/peepingtom#70]
Our data model went through some stuff, but it feels like it's reaching a state where it could stay for a while. I'm happy with the level of separation between data and depiction in the low-level stuff, and I'm happy with how the high-level `DataSet` object provides an interface to all of it, without borthering too much with keeping thinkgs separated.

In light of this, I propose to close the circle and go back to the name `Peeper`, instead of `DataSet` :)

**Comment by alisterburt** [comment]
hahah excellent - yeah this works for me and I like how easy it is to explain to people. 

"The main object in peepingtom is the peeper, the peeper contains datablocks, knows which ones come from which volume and how to depict them"

**Comment by brisvag** [comment]
Closed by #76.
