### ISSUE TITLE
'Alchemist' renaming proposal

### ISSUE THREAD

**Issue by alisterburt** [gutsche-lab/peepingtom#73]
I'm not convinced by the name `Alchemist` for something which takes blocks and makes new blocks... I don't think it's sufficiently descriptive, what're your thoughts?

I think I prefer something which conveys the operation/operator aspect, so something like `BlockOperator` is my first idea?

**Comment by brisvag** [comment]
I was just thinking the same! I'm gonna think about it a bit more, but `Operator` seems good!

**Comment by brisvag** [comment]
I'm changing my mind a bit on this: Referencing to an `operator` is very generic, which can lead to confusion in the code (does this variable called `operator` refer to a `BlockOperator` object, or a mathematical operator, or...?). On the other hand, `Alchemist` is not something that can be mixed up. Not saying it's a good name, just that `operator` is a bit too vague!

**Comment by alisterburt** [comment]
I see what you mean but it's only a problem if all of the `Operators` include the name `Operator` which I'm not convinced is necessary (we had the same discussion about the different block types, although there I agree that they should probably keep `Block` in the name.

I think with alchemists the pattern would probably be to name them for what they do, `Transformation`, `ShiftAlongVector` or whatever it might be. What do you reckon?

**Comment by brisvag** [comment]
Yeah I see what you mean... but I guess if we don't keep the base name in the classes then it's fine. Transformation and ShiftAlongVector are quite clear, actually.

**Comment by brisvag** [comment]
Closing this, since with #91 we removed this code.
