### ISSUE TITLE
RELION shift handling may be incorrect

### ISSUE THREAD

**Issue by alisterburt** [gutsche-lab/peepingtom#83]
RELION shifts are currently applied as rlnCoordinateXYZ + rlnOriginXYZ, it's possible that they should be applied as rlnCoordinateXYZ - rlnOriginXYZ, will confirm when I know more

**Comment by brisvag** [comment]
How do you propose to debug this?

**Comment by alisterburt** [comment]
It’s debugged and needs inverting (to rlnCoordinateX/Y/X - rlnOriginX/Y/Z) :)

**Comment by brisvag** [comment]
Lol, ok :P I didn't have any data at hand for which it would be obvious.
